package com.ycfd.userrole.entity;

import lombok.Data;

@Data
public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menuid
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.roleid
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    private Integer roleid;

    public RoleMenu(Integer roleid){
        this.roleid=roleid;
    }

    public RoleMenu(Integer roleid,Integer menuid){
        this.roleid=roleid;
        this.menuid = menuid;
    }

    public RoleMenu(Integer id, Integer menuid, Integer roleid) {
        this.id = id;
        this.menuid = menuid;
        this.roleid = roleid;
    }
}