package com.ycfd.userrole.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.ycfd.userrole.entity.RoleMenu;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RoleMenuMapper extends BaseMapper<RoleMenu> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Wed Jul 24 22:01:33 CST 2019
     */
    int updateByPrimaryKey(RoleMenu record);

    /**
     *
     * @param roleMenus
     */
    void batchInsert(@Param("roleMenus") List<RoleMenu> roleMenus) ;
}